[package]
name = "rufus-wasm"
version = "0.1.0"
authors = ["Martin Huschenbett <martin.huschenbett@posteo.me>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
lalrpop-util = "0.17.2"
rufus-core = { path = "../rufus-core" }
wasm-bindgen = "0.2"
