name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --locked
    - name: Format
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy -- --deny warnings
    - name: Test
      run: cargo test --locked
